inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml

inherit_from: .rubocop_todo.yml

# Unnecessary, 'cause rubocop-github already has it
# Metrics/LineLength:
#   Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Rails:
  Enabled: true
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
    - db/migrate/*.rb