language: ruby
rvm:
  - 2.3.1
cache: bundler
before_script:
  - psql -c 'create database flashcards_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
script:
  - bundle exec rake db:setup
  - bundle exec rake spec
services:
  postgresql
